import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/app/components/Header";
import ContentContainer from "@/app/components/ContentContainer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ContentContainer>
        {children}
      </ContentContainer>
      </body>
    </html>
  )
}
