import type { Metadata } from "next";
import "./globals.css";
import ContentContainer from "./components/ContentContainer";
import { ThemeProvider } from "next-themes";
import { poppins } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider attribute="class">
          <ContentContainer>
            {children}
          </ContentContainer>
        </ThemeProvider >
      </body>
    </html>
  );
}
